### ISSUE TITLE
Traceback (clean repo)

### ISSUE THREAD

**Issue by samdenty99** [appu1232/Discord-Selfbot#221]
Traceback on a fresh repo clone:
![image](https://user-images.githubusercontent.com/13242392/31409039-6de1e112-ae02-11e7-8a41-a209b1effa44.png)

**Comment by appu1232** [comment]
Must not be a completely fresh clone because it seems it detects the config.json is present and tries to run the bot and fails because no token is present. Therefore, it's taking you to the setup wizard. Just enter the token and it should work. If it's still not working, I recommend dragging the `run.bat` to a completely new and empty folder and running it there.

**Comment by samdenty99** [comment]
git clone https://github.com/appu1232/Discord-Selfbot
    cd Discord-Selfbot
    ./run_linuxmac.sh

Paste token, fails => ![image](https://user-images.githubusercontent.com/13242392/31410426-77705ac0-ae06-11e7-9259-f8da7aaecd5b.png)

Type it again => above screenshot

**Comment by appu1232** [comment]
Ah not sure why I thought this was Windows. Hm, you could go into the `config.json` file under the settings folder and pasting the token for `cmd_prefix` to see if that works. Otherwise, try joining the Discord and asking about this.

**Comment by samdenty99** [comment]
The token is already saved in that file hmm, I'll join the Discord Server
