### ISSUE TITLE
BOT doesn't delete the command imput 

### ISSUE THREAD

**Issue by marcocorriero** [appu1232/Discord-Selfbot#241]
i do >help 1 and the bot doesn't remove the command input, fixes?

**Comment by Bluscream** [comment]
That's a decision that was made by design. Last time i worked with the bot it was very inconsisten though (On some commands it deleted the output and it didn't with others)

It's not the worst idea since that
1. Makes it easier to remember/look up what command you used to achieve the output
2. Reduces traffic and theirfor the chance of getting flood-locked.

The bot creators could indeed add a config option to toggle auto input deletion for all commands tho.

**Comment by LyricLy** [comment]
@LucifersCircle This is not up to us. More likely, it is an issue with your mobile client. Try reloading and see if the commands disappear then. If they do, that is the case.

**Comment by LucifersCircle** [comment]
@LyricLy I've done that and the issue still happens however it is not frequent, (about 1 in 100) thank you for the clarification though!!
