### ISSUE TITLE
Error On Running 

### ISSUE THREAD

**Issue by VSabertail** [appu1232/Discord-Selfbot#244]
http://prntscr.com/hcopf6

**Comment by astronautlevel2** [comment]
Try reinstalling python 3

**Comment by Drakonas** [comment]
Actually @astronautlevel2 discord.webhooks seems to not be found by pip3 in its repositories.

**Comment by astronautlevel2** [comment]
That's a different issue than the one in OP's screenshot - OP is getting a WinError 31, whereas the discord.webhooks error would throw something else.

Additionally, the discord.webhooks package hasn't been needed for a while (2 months now iirc). Update to the latest version of the bot.

**Comment by Drakonas** [comment]
Sorry I was reading their error and it said a possible reason was missing dependency.

Not sure what you mean by "a while" because the latest release is from October 14th and it lists that as a dependency. So I guess I wasn't aware I'm supposed to use the repository. I usually don't like using cutting edge code due to possible bugs.

**Comment by astronautlevel2** [comment]
The [October 14th](https://i.imgur.com/cO1EF7m.png) release does not have discord.webhooks listed as a dependency.

**Comment by Drakonas** [comment]
@astronautlevel2 apologies. I did not copy the requirements.txt over. I will create another issue so I don't hijack this thread, because I am having an issue with another dependency.

**Comment by astronautlevel2** [comment]
Since OP hasn't responded, I'm going to close this.

It seems to be that this issue is with python 3.6 on Windows - Python 3.5.2 should work fine.
