### ISSUE TITLE
unable to use selfbot due to memory leaks and websocket connection.

### ISSUE THREAD

**Issue by ryudragon98** [appu1232/Discord-Selfbot#307]
the memory leaks and websocket connection are preventing me from using the selfbot at some times, in the logs on heroku i get `Something went wrong: WebSocket connection is closed: no code, no reason.` and `Error R14 (Memory quota exceeded)
 Process running mem=722M(141.1%)` with the mem number rising, when the bot does work it works for a while but will then again stop working and is trouble to get working again.

**Comment by LyricLy** [comment]
This error seems to be localized to Heroku.

**Comment by chenzw95** [comment]
This is not necessarily a memory leak - the bot's internal cache for messages and guild members is populated over time, and contributes to increasing memory usage.

The websockets-related issue is due to a bug in the websockets library - this has been temporarily mitigated with discord.py mandating a slightly older version of the library.
