### ISSUE TITLE
[Suggestions/Issues] Things found that could be changed

### ISSUE THREAD

**Issue by Jan200101** [appu1232/Discord-Selfbot#61]
- [x] loopself.py should be intergrated into appuselfbot.py
- [x] why set the directory as a git clone in run.bat
- [ ] errorst in run.bat are too vague
- [x] part of run.bat is very badly written.
For example [Line 34](https://github.com/appu1232/Discord-Selfbot/blob/master/run.bat#L43)
- [ ] text shouldnt be stored on the root directory
- [x] import * is bad for mulitple reasons for example it puts a lot of stuff into your namespace
- [x] make cogs optional so lessen the needed requirements
I would suggest making them silently fail with a small error to notify the user
- [x] allow for plain github repo download but with a warning
- [x] json files in settings can be generated and dont need to preexist
- [x] allowing the user to input a token if none is given

There are probably more but these are the ones I find the most notable from a dev and user endpoint 
(I will check these off if the feature has been added / Issue been resolved)

**Comment by Bluscream** [comment]
>  json files in settings can be generated and dont need to preexist

they are currently working on that one.

**Comment by appu1232** [comment]
> loopself.py should be intergrated into appuselfbot.py

This was done because some people may not want the bot to restart on crash. Found it simpler if they could just run appuselfbot.py then rather than loopself.py

> why set the directory as a git clone in run.bat

In order to git pull into the repo when using the update command. If git pull fails, the bot tries to force git clone again in order to update.

> errorst in run.bat are too vague

Possibly, although I didn't really try to make the most thorough batch file for that. I do realize requirements installation should be shown when being installed however, so I will work on changes like that.

> part of run.bat is very badly written. For example Line 34

No clue why that's there actually 🤔 Reworking run.bat is currently in progress anyway.

> text shouldnt be stored on the root directory

what text?

> import * is bad for mulitple reasons for example it puts a lot of stuff into your namespace

When importing checks.py right? That entire file is also being rewritten so imports will change as well.

> make cogs optional so lessen the needed requirements I would suggest making them silently fail with a small error to notify the user

It does fail silently and a small error in the run.bat if they fail to load. As for making it optional, people can just drag the cog out of the folder if they so choose. I honestly don't want to make everything tedious with installation and throw new users into cogs saying "this is how you add cogs, this is how you remove them, btw this is what a cog is." For now, no plans on making every cog optional.

> allow for plain github repo download but with a warning

Not sure what you mean. Plain github repo download does work, it's just the git repo needs to be initialized when running run.bat in order to check for updates.

> json files in settings can be generated and dont need to preexist

As Blue said, it's also being worked on.

> allowing the user to input a token if none is given

Being worked on.

Most of the changes that we are working on are occurring in config-manager branch.

Anyway, thanks for the input.

**Comment by LyricLy** [comment]
Been dead for ages and doesn't need to be open.
